# Generated by Django 4.2.7 on 2023-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders_history',
            field=models.JSONField(default=dict),
        ),
    ]
